camera:
  compression: mjpeg
  fps: 30                  # Frames per second for the camera feed
  width: 640               # Width and height of the camera feed
  height: 480              # Width and height of the camera feed
  motion_contour_area: 500 # Minimum contour area for motion detection (in pixels)
  motion_detection: true   # Motion detection is enabled by default

cameras:
- 0                        # Camera index (more can be added by specifying additional indices in the list)

record:
  enabled: true            # Whether recording is enabled or not
  recording_length: 1      # How long each recording should be in minutes
  storage_path: /home/user/optivue
  video_retention: 30      # How long to keep old recordings in days

server:
  host: 0.0.0.0            # Listen on all interfaces (can be changed to localhost for local access only)
  port: 5000               # Port to listen on
