camera:
  compression: mjpeg
  fps: 30
  height: 480
  motion_contour_area: 500
  motion_detection: true
  width: 640
cameras:
- 0
pipes:
  dir: /tmp/cam_pipes
record:
  enabled: true
  recording_length: 1
  storage_path: /home/miles/optivue/recordings
  video_retention: 30
server:
  host: 0.0.0.0
  port: 5000
